// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CrossFDTL
List CrossFDTL(NumericMatrix CovA, NumericMatrix CovB, double lambda, double rho, int maxiter);
RcppExport SEXP _SPDtrace_CrossFDTL(SEXP CovASEXP, SEXP CovBSEXP, SEXP lambdaSEXP, SEXP rhoSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type CovA(CovASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type CovB(CovBSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(CrossFDTL(CovA, CovB, lambda, rho, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// inference_Dtrace_solution_path
List inference_Dtrace_solution_path(NumericMatrix CovA, NumericMatrix CovB, int sparsityLevel);
RcppExport SEXP _SPDtrace_inference_Dtrace_solution_path(SEXP CovASEXP, SEXP CovBSEXP, SEXP sparsityLevelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type CovA(CovASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type CovB(CovBSEXP);
    Rcpp::traits::input_parameter< int >::type sparsityLevel(sparsityLevelSEXP);
    rcpp_result_gen = Rcpp::wrap(inference_Dtrace_solution_path(CovA, CovB, sparsityLevel));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SPDtrace_CrossFDTL", (DL_FUNC) &_SPDtrace_CrossFDTL, 5},
    {"_SPDtrace_inference_Dtrace_solution_path", (DL_FUNC) &_SPDtrace_inference_Dtrace_solution_path, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SPDtrace(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
