# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inference_Dtrace_solution_path <- function(CovA, CovB, sparsityLevel) {
    .Call(`_SPDtrace_inference_Dtrace_solution_path`, CovA, CovB, sparsityLevel)
}

